# Simplified Operator Deployment Structure
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-controller-operator
  namespace: redpanda-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: operator
    spec:
      containers:
      - name: manager
        image: docker.redpanda.com/redpandadata/redpanda-operator:v25.x.x
        args:
        - "--metrics-bind-address=:8080"
        - "--health-probe-bind-address=:8081"
        # Enable cluster-scope to manage multiple banking ledgers
        - "--cluster-sw-version-canary"